In [1]:
import numpy as np
import pandas as pd  


w = pd.DataFrame(data=np.load('train_seizure.npy'),columns=['file','begin','end','type','freq','time','montage'])
n = pd.DataFrame(data=np.load('train_n_seizure.npy'),columns=['file','freq','time','montage'])
#train_seizure.npy
print(w.shape)
w.head()

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [102]:
print(n.shape)
n.head()

(3730, 4)


file freq  time  \
0  train/01_tcp_ar/000/00000077/s003_2010_01_21/0...  250  1205   
1  train/01_tcp_ar/002/00000254/s005_2010_11_15/0...  250  1442   
2  train/01_tcp_ar/002/00000254/s006_2011_07_01/0...  250  1197   
3  train/01_tcp_ar/002/00000254/s007_2013_03_25/0...  250  1244   
4  train/01_tcp_ar/002/00000272/s007_2003_07_03/0...  400   194   

                                             montage  
0  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
1  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
2  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
3  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
4  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...

In [103]:
ind1, ct1 = np.unique(w['freq'],return_counts=True)
ind2, ct2 = np.unique(n['freq'],return_counts=True)
print(ind1)
print(ct1)
print(ind2)
print(ct2)

######################
'''
Serão usados .edf com
freq amostra de 256hz
'''

[250 256 400 512 1000]
[ 825 1217  276   16   36]
[250 256 400 512 1000]
[ 687 2522  400   82   39]


'\nSerão usados .edf com\nfreq amostra de 256hz\n'

In [104]:
w = w[w['freq']==256]
n = n[n['freq']==256]
w.index = np.arange(len(w))
n.index = np.arange(len(n))

print(w.shape)
print(n.shape)

(1217, 7)
(2522, 4)


In [105]:
ind1, ct1 = np.unique(w['montage'],return_counts=True)
ind2, ct2 = np.unique(n['montage'],return_counts=True)

print(len(ind1))
print(len(ind2))
print(ct1)
print(ct2)

26
33
[ 23  32   3 114  11 197  90  41 204   8   4 272  20  11  11  38   4  17
  16   4   1  33  17  43   1   2]
[  6  15 154   1 349 100 105  85   3  36   3   1 397  91   6 165   1 209
   4 144  20 372  56  31  21   5   1  29  55  32   7   5  13]


In [106]:
aux_ind1=[]
aux_ind2=[]

for i in range(len(ind1)):
    if 'EMG-REF' in ind1[i]:
        aux_ind1.append(i)
        
for i in range(len(ind2)):
    if 'EMG-REF' in ind2[i]:
        aux_ind2.append(i)

In [107]:
print(ct1[aux_ind1])
print(ct2[aux_ind2])

[272  20  11  11   4  17  16   1  33  17  43   1   2]
[165   1 209   4 144  20  56  31   1  29  55  32   7   5]


In [108]:
print(len(ind1[11]),len(ind2[15]))
print(len(ind1[11])==len(ind2[15]))
for i in range(len(ind1[11])):
    print(ind1[11][i],ind2[15][i])

34 34
True
EEG FP1-REF EEG FP1-REF
EEG FP2-REF EEG FP2-REF
EEG F3-REF EEG F3-REF
EEG F4-REF EEG F4-REF
EEG C3-REF EEG C3-REF
EEG C4-REF EEG C4-REF
EEG P3-REF EEG P3-REF
EEG P4-REF EEG P4-REF
EEG O1-REF EEG O1-REF
EEG O2-REF EEG O2-REF
EEG F7-REF EEG F7-REF
EEG F8-REF EEG F8-REF
EEG T3-REF EEG T3-REF
EEG T4-REF EEG T4-REF
EEG T5-REF EEG T5-REF
EEG T6-REF EEG T6-REF
EEG T1-REF EEG T1-REF
EEG T2-REF EEG T2-REF
EEG FZ-REF EEG FZ-REF
EEG CZ-REF EEG CZ-REF
EEG PZ-REF EEG PZ-REF
EEG EKG1-REF EEG EKG1-REF
EEG C3P-REF EEG C3P-REF
EEG C4P-REF EEG C4P-REF
EEG SP1-REF EEG SP1-REF
EEG SP2-REF EEG SP2-REF
EMG-REF EMG-REF
EEG 29-REF EEG 29-REF
EEG 30-REF EEG 30-REF
EEG 31-REF EEG 31-REF
EEG 32-REF EEG 32-REF
IBI IBI
BURSTS BURSTS
SUPPR SUPPR


In [109]:
print(ind1[11])

['EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG T1-REF', 'EEG T2-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF', 'EEG EKG1-REF', 'EEG C3P-REF', 'EEG C4P-REF', 'EEG SP1-REF', 'EEG SP2-REF', 'EMG-REF', 'EEG 29-REF', 'EEG 30-REF', 'EEG 31-REF', 'EEG 32-REF', 'IBI', 'BURSTS', 'SUPPR']


In [110]:
index_w = []
index_n = []

for i in range(len(w)):
    if list(w['montage'])[i]==ind1[11]:
        index_w.append(i)

for i in range(len(n)):
    if list(n['montage'])[i]==ind1[11]:
        index_n.append(i)

In [111]:
w = w.iloc[index_w,:]
n = n.iloc[index_n,:]

w.index = np.arange(len(w))
n.index = np.arange(len(n))

In [112]:
w.head(10)

file    begin      end  type  \
0  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  86.9922  115.207  FNSZ   
1  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  189.973  209.109  FNSZ   
2  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  338.949  358.004  FNSZ   
3  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  20.9375  47.2656  FNSZ   
4  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  109.027  136.789  FNSZ   
5  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  184.012  211.906  FNSZ   
6  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  290.012  322.676  FNSZ   
7  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  388.012   414.18  FNSZ   
8  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  432.012  446.062  FNSZ   
9  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  547.012  560.012  FNSZ   

  freq time                                            montage  
0  256  391  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
1  256  391  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
2  256  391  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
3  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
4  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
5  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
6  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
7  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
8  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
9  256  603  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...

In [113]:
n.head(10)

file freq  time  \
0  train/03_tcp_ar_a/028/00002886/s006_2011_03_08...  256   826   
1  train/03_tcp_ar_a/028/00002886/s006_2011_03_08...  256   601   
2  train/03_tcp_ar_a/028/00002886/s006_2011_03_08...  256   333   
3  train/03_tcp_ar_a/029/00002991/s004_2010_04_26...  256   601   
4  train/03_tcp_ar_a/029/00002991/s005_2010_04_27...  256   601   
5  train/03_tcp_ar_a/029/00002991/s005_2010_04_27...  256   601   
6  train/03_tcp_ar_a/029/00002991/s005_2010_04_27...  256   601   
7  train/03_tcp_ar_a/029/00002991/s005_2010_04_27...  256   601   
8  train/03_tcp_ar_a/061/00006175/s003_2011_04_28...  256   601   
9  train/03_tcp_ar_a/064/00006413/s005_2010_02_15...  256  1593   

                                             montage  
0  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
1  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
2  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
3  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
4  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
5  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
6  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
7  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
8  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
9  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...

In [114]:
np.save('w_train.npy',w)
np.save('n_train.npy',n)