In [45]:
import numpy as np
import pandas as pd
import os

path  = os.getcwd()
path2 = '/home/pib3/Projetos/tuh_eeg_seizures/dev_test/01_tcp_ar/'


file = np.load(path + '/docs/data_ecg_emg.npy')
col = ['paths','freq','montage','type','start','end','class']
data = pd.DataFrame(data=file,columns=col)
print(data.shape)
data 

(239, 7)


paths freq  \
0    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
1    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
2    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
3    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
4    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
5    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
6    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
7    065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
8    065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
9    065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
10   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
11   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
12   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
13   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
14   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
15   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
16   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
17   065/00006546/s021_2012_02_22/00006546_s021_t00...  256   
18   065/00006546/s021_2012_02_22/00006546_s021_t01...  256   
19   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
20   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
21   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
22   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
23   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
24   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
25   065/00006546/s022_2012_02_23/00006546_s022_t00...  256   
26   065/00006546/s022_2012_02_23/00006546_s022_t01...  256   
27   065/00006546/s023_2012_02_24/00006546_s023_t00...  256   
28   065/00006546/s023_2012_02_24/00006546_s023_t00...  256   
29   065/00006546/s023_2012_02_24/00006546_s023_t00...  256   
..                                                 ...  ...   
209  088/00008889/s004_2012_03_21/00008889_s004_t01...  256   
210  088/00008889/s004_2012_03_21/00008889_s004_t01...  256   
211  088/00008889/s004_2012_03_21/00008889_s004_t01...  256   
212  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
213  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
214  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
215  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
216  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
217  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
218  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
219  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
220  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
221  088/00008889/s005_2012_03_22/00008889_s005_t00...  256   
222  088/00008889/s005_2012_03_22/00008889_s005_t01...  256   
223  088/00008889/s005_2012_03_22/00008889_s005_t01...  256   
224  088/00008889/s005_2012_03_22/00008889_s005_t01...  256   
225  095/00009570/s002_2012_11_05/00009570_s002_t00...  256   
226  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
227  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
228  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
229  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
230  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
231  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
232  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
233  101/00010106/s002_2013_02_08/00010106_s002_t00...  256   
234  101/00010106/s003_2013_02_09/00010106_s003_t00...  256   
235  101/00010106/s003_2013_02_09/00010106_s003_t00...  256   
236  101/00010106/s003_2013_02_09/00010106_s003_t00...  256   
237  101/00010106/s003_2013_02_09/00010106_s003_t00...  256   
238  101/00010106/s003_2013_02_09/00010106_s003_t00...  256   

                                               montage  \
0    [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
1    [EEG FP1-REF, EEG FP2

In [50]:
np.unique(data['montage'][0])

array(['BURSTS', 'EEG 31-REF', 'EEG 32-REF', 'EEG A1-REF', 'EEG A2-REF',
       'EEG C3-REF', 'EEG C3P-REF', 'EEG C4-REF', 'EEG C4P-REF',
       'EEG CZ-REF', 'EEG EKG1-REF', 'EEG F3-REF', 'EEG F4-REF',
       'EEG F7-REF', 'EEG F8-REF', 'EEG FP1-REF', 'EEG FP2-REF',
       'EEG FZ-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG P3-REF',
       'EEG P4-REF', 'EEG PZ-REF', 'EEG SP1-REF', 'EEG SP2-REF',
       'EEG T1-REF', 'EEG T2-REF', 'EEG T3-REF', 'EEG T4-REF',
       'EEG T5-REF', 'EEG T6-REF', 'EMG-REF', 'IBI', 'SUPPR'],
      dtype='<U12')

In [51]:
use = ['EEG C3-REF', 'EEG C4-REF','EEG CZ-REF', 'EEG EKG1-REF', 
       'EEG F3-REF', 'EEG F4-REF','EEG F7-REF', 'EEG F8-REF', 
       'EEG FP1-REF', 'EEG FP2-REF','EEG FZ-REF', 'EEG O1-REF', 
       'EEG O2-REF', 'EEG P3-REF','EEG P4-REF', 'EEG PZ-REF', 
       'EEG T1-REF', 'EEG T2-REF', 'EEG T3-REF', 'EEG T4-REF',
       'EEG T5-REF', 'EEG T6-REF', 'EMG-REF']

In [46]:
com_crise = data[data['type']!='bckg']
sem_crise = data[data['type']=='bckg']

com_crise.index = np.arange(len(com_crise))
sem_crise.index = np.arange(len(sem_crise))

print(com_crise.shape)
print(sem_crise.shape)


(93, 7)
(146, 7)


### Concatenando janelas com crise

In [47]:
com_crise.head(3)

paths freq  \
0  065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
1  065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
2  065/00006546/s020_2012_01_30/00006546_s020_t00...  256   

                                             montage  \
0  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
1  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
2  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   

                                         type  \
0              [bckg, fnsz, bckg, fnsz, bckg]   
1  [bckg, fnsz, bckg, fnsz, bckg, fnsz, bckg]   
2              [bckg, fnsz, bckg, fnsz, bckg]   

                                               start  \
0       [0.0, 86.3594, 126.6602, 260.2188, 297.4219]   
1  [0.0, 49.9922, 92.1445, 207.9922, 242.1602, 41...   
2        [0.0, 18.5547, 45.0547, 155.8516, 183.5547]   

                                                 end class  
0     [86.3594, 126.6602, 260.2188, 297.4219, 300.0]     1  
1  [49.9922, 92.1445, 207.9922, 242.1602, 412.210...     1  
2      [18.5547, 45.0547, 155.8516, 183.5547, 300.0]     1

In [48]:
inicio = []
fim = []

for i in range(len(com_crise)):
    aux_i = []
    aux_f = []
    for ii in range(1,len(com_crise.loc[i,'start'])):
        if ii%2!=0:
            aux_i.append(com_crise.loc[i,'start'][ii])
            aux_f.append(com_crise.loc[i,'end'][ii])
    inicio.append(np.array(aux_i))
    fim.append(np.array(aux_f))


In [52]:
for i in range(len(inicio)):
    print(inicio[i],fim[i])
    print()

[ 86.3594 260.2188] [126.6602 297.4219]

[ 49.9922 207.9922 412.2109] [ 92.1445 242.1602 450.3672]

[ 18.5547 155.8516] [ 45.0547 183.5547]

[ 39.8516 197.0391 323.9531 471.7578] [ 69.2773 247.0352 371.9531 495.1602]

[ 32.0156 188.9727] [ 72.7578 231.9727]

[113.7813 283.1328 457.8398] [140.4063 313.8516 499.2188]

[ 46.4453 296.9141 564.8516] [ 75.0469 345.1133 630.0547]

[297.9805] [353.5781]

[209.9609] [273.4492]

[ 304.5547 1770.8203] [ 360.0391 1826.0195]

[415.2227] [447.918]

[215.6719] [243.4805]

[ 1.     40.9414] [22.8867 65.0391]

[173.7813] [199.0781]

[301.5391] [351.3945]

[ 83.9805 311.0469 460.9609 537.9531] [105.0781 351.0469 511.9609 579.9531]

[159.9531] [212.3047]

[222.2344 413.7539] [321.5313 447.6523]

[307.4609] [370.082]

[209.5547 271.7813 426.8594] [255.4531 330.6797 508.1602]

[169.5469 194.3555] [188.8477 220.9531]

[ 24.2617 240.9727 294.3477] [ 57.1602 286.5742 320.3477]

[125.0469 253.4805 499.7461] [218.5469 292.0781 550.1484]

[234.6797 741.5547] [29

In [85]:
import mne

fs = 256
mx_w = np.ones((23,1))
for i in range(len(com_crise)):
    raw = mne.io.read_raw_edf(path2 + com_crise.loc[i,'paths'],preload=True,verbose=False)
    sig = raw.to_data_frame().T
    sig = sig.loc[use,:].to_numpy()
    
    dur = np.array([inicio[i],fim[i]]).astype('int')
    
    for ii in range(len(dur[0])):
        mx_w = np.hstack((mx_w,sig[:,fs*dur[0,ii]:fs*dur[1,ii]]))
    


Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int6

In [87]:
mx_w.shape

(23, 2837505)

### Concatenando Janelas sem crise

In [89]:
sem_crise.head(3)

paths freq  \
0  065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
1  065/00006546/s020_2012_01_30/00006546_s020_t00...  256   
2  065/00006546/s021_2012_02_22/00006546_s021_t00...  256   

                                             montage  type start  end class  
0  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  bckg     0  300     0  
1  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  bckg     0  300     0  
2  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  bckg     0  300     0

In [93]:
# inicio = []
# fim = []

# for i in range(len(com_crise)):
#     aux_i = []
#     aux_f = []
#     for ii in range(1,len(com_crise.loc[i,'start'])):
#         if ii%2!=0:
#             aux_i.append(com_crise.loc[i,'start'][ii])
#             aux_f.append(com_crise.loc[i,'end'][ii])
#     inicio.append(np.array(aux_i))
#     fim.append(np.array(aux_f))
mx_n = np.ones((23,1))

for i in range(len(sem_crise)):
    #print(int(sem_crise.loc[i,'start']),int(sem_crise.loc[i,'end']))
    raw = mne.io.read_raw_edf(path2 + sem_crise.loc[i,'paths'],preload=True,verbose=False)
    sig = raw.to_data_frame().T
    sig = sig.loc[use,:].to_numpy()
    
    inicio = int(sem_crise.loc[i,'start'])
    fim = int(sem_crise.loc[i,'end'])
    
    mx_n = np.hstack((mx_n,sig[:,fs*inicio:fs*fim]))
    
mx_n.shape

Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int64'>"...
Converting "time" to "<class 'numpy.int6

(23, 16552193)

In [94]:
np.save('matriz_com_crise.npy',mx_w)
np.save('matriz_sem_crise.npy',mx_n)